CREATE SCHEMA bot;

GO

create table bot.state_data (
       id int8 generated by default as identity,
       user_id bigserial not null,
       chat_id bigserial not null,
       state int4,
       primary key (id)
    );